"""baseline schema

Revision ID: b29ad92612b1
Revises: 
Create Date: 2026-08-24 08:16:48.731171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29ad92612b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=128), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_command'), 'audit_records', ['command'], unique=False)
    op.create_index(op.f('ix_audit_records_user_id'), 'audit_records', ['user_id'], unique=False)
    op.create_table('automation_definitions',
    sa.Column('automation_id', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('automation_id')
    )
    op.create_table('automation_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automation_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_automation_id'), 'automation_executions', ['automation_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('shift', sa.String(length=32), nullable=True),
    sa.Column('pending_command', sa.String(length=128), nullable=True),
    sa.Column('pending_parameters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_automation_executions_automation_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_table('automation_definitions')
    op.drop_index(op.f('ix_audit_records_user_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_command'), table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
