from __future__ import annotations

from datetime import date
from typing import Protocol

from hotel_chatbot_v2.models.pms import (
    Guest,
    Incident,
    Reservation,
    Room,
    RoomStatus,
)


class PMSInterface(Protocol):
    def search_guests(self, name: str) -> list[Guest]: ...
    def get_reservation(self, reservation_id: str | None = None, guest_name: str | None = None) -> list[Reservation]: ...
    def get_arrivals(self, on_date: date) -> list[Reservation]: ...
    def get_departures(self, on_date: date) -> list[Reservation]: ...
    def get_room(self, room_number: str) -> Room | None: ...
    def get_rooms(self, status: RoomStatus | None = None) -> list[Room]: ...
    def mark_room_clean(self, room_number: str) -> Room: ...
    def get_incidents(self, status: str | None = None) -> list[Incident]: ...
    def create_incident(self, room_number: str | None, incident_type: str, description: str) -> Incident: ...
    def resolve_incident(self, incident_id: str) -> Incident: ...
